set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display "tmux config reloaded"

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
